### PR TITLE
Create Blogs.java

### PR DESCRIPTION
**Pull request by Get-DevVed-YT**

### CODE REVIEW

**Comment by Aktindo** [comment]
Great! Will be merged into the v0.3.0b branch.

**Comment by YT-GameWorks** [comment]
hello there! thanks! will be merged (sooner or later :) )

**Comment by YT-GameWorks** [comment]
Hey there! will me merged after 0.3.0b merges into main

**Review by Aktindo — APPROVED** [review]
Very well then!

**Review by YT-GameWorks — CHANGES_REQUESTED** [review]
Dosen't seem like you registered the listener in the main class, please do so!

**Comment by Aktindo** [comment]
Oh I didn't see that!

**Review by Aktindo — CHANGES_REQUESTED** [review]
Please add its listener in the main file. Ty!

**Comment by Aktindo** [comment]
Ready to be merged

**Pull request merged**
